spring:
  application:
    name: vet-manager-api
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:vet_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password

server:
  port: 8000