-- PET
INSERT INTO PET (NAME, VERSION, CREATED_AT, UPDATED_AT) VALUES ('Fluffy', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);   -- 1
INSERT INTO PET (NAME, VERSION, CREATED_AT, UPDATED_AT) VALUES ('Bella', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);    -- 2
INSERT INTO PET (NAME, VERSION, CREATED_AT, UPDATED_AT) VALUES ('Charlie', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);  -- 3
INSERT INTO PET (NAME, VERSION, CREATED_AT, UPDATED_AT) VALUES ('Lucy', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);     -- 4
INSERT INTO PET (NAME, VERSION, CREATED_AT, UPDATED_AT) VALUES ('Max', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);      -- 5

-- SERVICE
INSERT INTO SERVICE (NAME, COST, CURRENCY, VERSION, CREATED_AT, UPDATED_AT) VALUES ('Grooming', 30.0, 'RON', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);        -- 1
INSERT INTO SERVICE (NAME, COST, CURRENCY, VERSION, CREATED_AT, UPDATED_AT) VALUES ('Vaccination', 20.0, 'RON', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);     -- 2
INSERT INTO SERVICE (NAME, COST, CURRENCY, VERSION, CREATED_AT, UPDATED_AT) VALUES ('Neutering', 100.0, 'RON', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);      -- 3
INSERT INTO SERVICE (NAME, COST, CURRENCY, VERSION, CREATED_AT, UPDATED_AT) VALUES ('Dental Cleaning', 50.0, 'RON', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); -- 4
INSERT INTO SERVICE (NAME, COST, CURRENCY, VERSION, CREATED_AT, UPDATED_AT) VALUES ('Microchipping', 60.0, 'RON', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);   -- 5

-- DOCTOR
INSERT INTO DOCTOR (FIRST_NAME, LAST_NAME, VERSION, CREATED_AT, UPDATED_AT) VALUES ('John', 'Smith', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);         -- 1
INSERT INTO DOCTOR (FIRST_NAME, LAST_NAME, VERSION, CREATED_AT, UPDATED_AT) VALUES ('Robert', 'Johnson', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);     -- 2
INSERT INTO DOCTOR (FIRST_NAME, LAST_NAME, VERSION, CREATED_AT, UPDATED_AT) VALUES ('Michael', 'Williams', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);   -- 3
INSERT INTO DOCTOR (FIRST_NAME, LAST_NAME, VERSION, CREATED_AT, UPDATED_AT) VALUES ('David', 'Jones', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);        -- 4
INSERT INTO DOCTOR (FIRST_NAME, LAST_NAME, VERSION, CREATED_AT, UPDATED_AT) VALUES ('James', 'Brown', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);        -- 5

-- APPOINTMENT
INSERT INTO APPOINTMENT (DATE, PET_ID, DOCTOR_ID, VERSION, CREATED_AT, UPDATED_AT) VALUES ('2024-06-01', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);  -- 1
INSERT INTO APPOINTMENT (DATE, PET_ID, DOCTOR_ID, VERSION, CREATED_AT, UPDATED_AT) VALUES ('2024-07-01', 2, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);  -- 2
INSERT INTO APPOINTMENT (DATE, PET_ID, DOCTOR_ID, VERSION, CREATED_AT, UPDATED_AT) VALUES ('2024-08-01', 3, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);  -- 3
INSERT INTO APPOINTMENT (DATE, PET_ID, DOCTOR_ID, VERSION, CREATED_AT, UPDATED_AT) VALUES ('2024-09-01', 4, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);  -- 4
INSERT INTO APPOINTMENT (DATE, PET_ID, DOCTOR_ID, VERSION, CREATED_AT, UPDATED_AT) VALUES ('2024-10-01', 5, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);  -- 5

-- APPOINTMENT_SERVICE
INSERT INTO APPOINTMENT_SERVICE (APPOINTMENT_ID, SERVICE_ID) VALUES (1, 1); -- 1
INSERT INTO APPOINTMENT_SERVICE (APPOINTMENT_ID, SERVICE_ID) VALUES (1, 2); -- 2
INSERT INTO APPOINTMENT_SERVICE (APPOINTMENT_ID, SERVICE_ID) VALUES (1, 3); -- 3
INSERT INTO APPOINTMENT_SERVICE (APPOINTMENT_ID, SERVICE_ID) VALUES (2, 4); -- 4
INSERT INTO APPOINTMENT_SERVICE (APPOINTMENT_ID, SERVICE_ID) VALUES (3, 5); -- 5