-- PET
INSERT INTO PET (NAME, VERSION, CREATED_AT, UPDATED_AT)
VALUES ('Fluffy', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  -- 1
       ('Bella', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),   -- 2
       ('Charlie', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 3
       ('Luna', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),    -- 4
       ('Lucy', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),    -- 5
       ('Max', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);     -- 6

-- SERVICE
INSERT INTO SERVICE (NAME, COST, CURRENCY, VERSION, CREATED_AT, UPDATED_AT)
VALUES ('Grooming', 30.0, 'RON', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),        -- 1
       ('Vaccination', 20.0, 'RON', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),     -- 2
       ('Neutering', 100.0, 'RON', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),      -- 3
       ('Dental Cleaning', 50.0, 'RON', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 4
       ('Microchipping', 60.0, 'RON', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);   -- 5

-- DOCTOR
INSERT INTO DOCTOR (FIRST_NAME, LAST_NAME, VERSION, CREATED_AT, UPDATED_AT)
VALUES ('John', 'Smith', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),       -- 1
       ('Robert', 'Johnson', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),   -- 2
       ('Michael', 'Williams', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 3
       ('David', 'Jones', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),      -- 4
       ('James', 'Brown', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);      -- 5

-- APPOINTMENT
INSERT INTO APPOINTMENT (DATE, PET_ID, DOCTOR_ID, VERSION, CREATED_AT, UPDATED_AT)
VALUES ('2024-06-01', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 1
       ('2024-07-01', 2, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 2
       ('2024-08-01', 3, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 3
       ('2024-09-01', 4, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 4
       ('2024-10-01', 5, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 5
       ('2024-11-01', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 6
       ('2024-12-01', 2, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 7
       ('2025-01-01', 3, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 8
       ('2025-02-01', 4, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 9
       ('2025-03-01', 5, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 10
       ('2025-04-01', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 11
       ('2025-05-01', 2, 2, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 12
       ('2025-06-01', 3, 3, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 13
       ('2025-07-01', 4, 4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- 14
       ('2025-08-01', 5, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); -- 15


-- APPOINTMENT_SERVICE
INSERT INTO APPOINTMENT_SERVICE (APPOINTMENT_ID, SERVICE_ID)
VALUES (1, 1),  -- 1
       (1, 2),  -- 2
       (1, 3),  -- 3
       (2, 4),  -- 4
       (3, 5),  -- 5
       (4, 1),  -- 6
       (5, 2),  -- 7
       (6, 3),  -- 8
       (7, 4),  -- 9
       (8, 5),  -- 10
       (9, 1),  -- 11
       (10, 2), -- 12
       (11, 3), -- 13
       (12, 4), -- 14
       (13, 5), -- 15
       (14, 1), -- 16
       (15, 2); -- 17

-- USER_INFO
INSERT INTO user_info (email, username, password, roles)
VALUES ('user1@example.com', 'user1', '$2y$10$Q79zuOsg4yzvcwt4Buv9LuSkpDL5hhLQetMHS5f9o9IdYIBlmH.uC', 'ROLE_USER'), -- 1
       ('user2@example.com', 'user2', '$2y$10$elrvBEXZZHRFcKXd4/Ndj.WoOZHjoXsOgeT81pByseoyLILdKOZDm', 'ROLE_USER'), -- 2
       ('user3@example.com', 'user3', '$2y$10$tN5zAUj.QYSbRwP328g/U.QJPgFYpvuBppDlYOq8TUkNFIDHMz6f6', 'ROLE_USER'), -- 3
       ('user4@example.com', 'user4', '$2y$10$h4De0qce/JbIq5PYtF2s8ujImk5GiZnHLsStZ5/7vBpyxW3jqTMQm', 'ROLE_USER'), -- 4
       ('user5@example.com', 'user5', '$2y$10$fxCtRYZzfffdlgLBvNnSs.6n/KXj9PJyKGLJaaKN3b7PGJT0Z5g82', 'ROLE_USER'); -- 5